<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxi9xEs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxi9xEs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxi9xEs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxi9xEs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxi9xEs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ixi9xEs',
    'container.build_id' => '204fd920',
    'container.build_time' => 1646575197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxi9xEs');
