<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXsNrgxq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXsNrgxq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXsNrgxq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXsNrgxq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXsNrgxq\App_KernelDevDebugContainer([
    'container.build_hash' => 'XsNrgxq',
    'container.build_id' => '804145b3',
    'container.build_time' => 1649417283,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXsNrgxq');
